# Generated by Django 4.2.3 on 2023-07-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_student_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_type',
            field=models.CharField(default='Undeclared', max_length=100),
        ),
    ]
