# Generated by Django 4.2.3 on 2023-07-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(default='Undeclared', max_length=50, unique=b'I01\n'),
        ),
    ]
