# Generated by Django 4.2.3 on 2023-07-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
