# Generated by Django 4.2.3 on 2023-07-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_student_batch_alter_student_course_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.TextField()),
                ('credit_hours', models.IntegerField()),
                ('course_image', models.ImageField(upload_to='course_images/')),
                ('course_type', models.CharField(max_length=100)),
            ],
        ),
    ]
