# Generated by Django 4.2.3 on 2023-08-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_description', models.TextField()),
                ('course_image', models.ImageField(upload_to='course_images/')),
                ('Service_type', models.CharField(max_length=100)),
            ],
        ),
    ]
