# Generated by Django 4.2.3 on 2023-08-02 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='course_image',
            new_name='service_image',
        ),
    ]
