# Generated by Django 4.2.4 on 2023-08-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_rename_course_image_services_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_pdf',
            field=models.FileField(blank=True, upload_to='course_pdfs/'),
        ),
    ]
