# Generated by Django 4.2.4 on 2023-08-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_course_course_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='course_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_pdf',
        ),
        migrations.AddField(
            model_name='course',
            name='course_files',
            field=models.ManyToManyField(related_name='courses', to='students.coursefile'),
        ),
    ]
